### ISSUE TITLE
Gulp issue: sauvegarde pendant la compilation

### ISSUE THREAD

**Issue by francoispothier** [libeo/vtt#18]
Dans les gros projets une compilation gulp peut prendre 1.53min.
Si on sauvegarde pendant une compile, gulp plante et emporte une partie de patience avec lui.

**Comment by lefoy** [comment]
I need more information on this issue to solve it. What task fails when compiling?
The compilation should not take 1 min, if that is the case, please let me know so I can take a look at why the compilation takes so long.
