### ISSUE TITLE
Limit simultaneous processes in gulp-svg2png

### ISSUE THREAD

**Issue by fcapovilla** [libeo/vtt#22]
gulp-svg2png doesn't limit the number of concurrent processes when converting svg files to png. This is problematic for projects with a huge number of svg files, because machines with limited memory might swap and hang because of the huge memory requirement.

A fix was proposed in the official repository, but still isn't on master :
https://github.com/akoenig/gulp-svg2png/issues/7

A fork was temporarily created on our gitlab to fix this issue while waiting for a fix on the official repository. To use this fork, replace the gulp-svg2png line in package.json with this line : 
`"gulp-svg2png": "git+ssh://git@gitlab.libeo.com:36220/fcapovilla/gulp-svg2png.git#feature/concurrency_limit",`

Should we wait for the bug to be fixed on the official repository, or should we move our fork on github so the bug can be fixed in vtt?

**Comment by akoenig** [comment]
This should be fixed now. The version `1.0.0` of `gulp-svg2png` supports a `concurrency` flag with which you can set the concurrent running transformations manually.

**Comment by lefoy** [comment]
Thanks for the update @akoenig !
