### ISSUE TITLE
NPM Caching

### ISSUE THREAD

**Issue by marcboivin** [libeo/vtt#24]
Right now for every release, everything is fetched from the internet. Slows the process down. NPM seems to have caching available. 

We need to implement some kind of caching to enable fast deployment. 

15 minutes is too slow, aiming under 5 minutes would be great. 1 minute would be the sweet spot.

**Comment by lefoy** [comment]
It's possible to use npm-cache to install dependencies.
Install npm-cache and use `npm-cache install` instead of `npm install`

https://www.npmjs.com/package/npm-cache
